# This is a xenial base with python 3.5 as well
FROM python:3.10.9-slim-bullseye AS builder
#FROM python:3.7.9-slim-stretch AS builder

#FROM ubuntu:xenial


RUN apt-get update \
    && apt-get install -y \
       wget \
       git \
       automake \
       autoconf \
       cmake \
       make \
       ca-certificates \
       openssl \
       # These two for activemq \       
       libaprutil1-dev \
       mariadb-client \
       python3-dev \ 
       python3-pip \
       python3-setuptools \
       sudo \
       vim \
       # state-estimator \
       liblapack-dev \
       libblas-dev \
       #libssl1.0-dev \
       libssl-dev \
       # helics \
       libboost-dev \
       libzmq5-dev \
       m4 \
       procps \
       libtool \
    && rm -rf /var/lib/apt/lists/* \
    && rm -rf /var/cache/apt/archives/*
#    && sudo /usr/bin/update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 1 \
#    && sudo /usr/bin/update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 1 \
#    && sudo sudo /usr/bin/update-alternatives  --set gcc /usr/bin/gcc-6 \
#    && sudo sudo /usr/bin/update-alternatives  --set g++ /usr/bin/g++-6 \
#       g++-6 \
#       gcc-6 \

# Build and install gcc 8
#RUN cd /opt \
    #&& wget http://ftp.mirrorservice.org/sites/sourceware.org/pub/gcc/releases/gcc-8.4.0/gcc-8.4.0.tar.gz \
    #&& tar zxf gcc-8.4.0.tar.gz \
    #&& cd gcc-8.4.0 \
    #&& ./contrib/download_prerequisites \
    #&& apt -y install build-essential \
    #&& ./configure --disable-multilib \
    #&& make -j 4 \
    #&& make install \
    #&& cd \
    #&& rm -rf /opt/gcc-8.4.0 /opt/gcc-8.4.0.tar.gz \
    #&& sudo /usr/bin/update-alternatives --install /usr/bin/gcc gcc /usr/local/bin/gcc 1 \
    #&& sudo /usr/bin/update-alternatives --install /usr/bin/g++ g++ /usr/local/bin/g++ 1 \
    #&& sudo sudo /usr/bin/update-alternatives  --set gcc /usr/local/bin/gcc \
    #&& sudo sudo /usr/bin/update-alternatives  --set g++ /usr/local/bin/g++

# Build and install cmake >= 10 
RUN cd /opt \
    && wget https://github.com/Kitware/CMake/releases/download/v3.20.3/cmake-3.20.3.tar.gz \
    && tar zxf cmake-3.20.3.tar.gz \
    && cd cmake-3.20.3 \
    && ./bootstrap \
    && make \
    && make install \
    && cd \
    && rm -rf /opt/cmake-3.20.3 cmake-3-20.3.tar.gz
